Pagen/Controllers/DecanatController.cs
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using Pagen.Models;
using Pagen.Models.Identity;

namespace Pagen.Controllers
{
    [Authorize(Roles = "decanat")]
    public class DecanatController : Controller
    {
        #region Readonly fields

        private readonly ApplicationContext
            _applicationContext = new ApplicationContext();

        #endregion

        #region Public methods

        [HttpGet]
        public ActionResult AllStudents()
        {
            return View(_applicationContext.Students.ToList());
        }

        [HttpGet]
        public ActionResult DeleteStudent(int id)
        {
            Student student = _applicationContext.Students.Find(id);
            if (student == null)
            {
                return Content("Студент не найден.");
            }

            _applicationContext.Entry(student).State =
                EntityState.Deleted;

            _applicationContext.SaveChanges();

            return RedirectToAction("AllStudents");
        }

        [HttpGet]
        public ActionResult EditStudent(int id)
        {
            Student student = _applicationContext.Students.Find(id);
            if (student == null)
            {
                return Content("Студент не найден.");
            }

            return View(student);
        }

        [HttpPost]
        public ActionResult EditStudent(Student student)
        {
            if (student == null)
            {
                return Content("Студент не создан.");
            }

            _applicationContext.Entry(student).State =
                EntityState.Modified;

            _applicationContext.SaveChanges();

            return RedirectToAction("AllStudents");
        }

        [HttpGet]
        public ActionResult CreateStudent()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateStudent(Student student)
        {
            if (student == null)
            {
                return Content("Студент не создан.");
            }

            _applicationContext.Students.Add(student);

            _applicationContext.SaveChanges();

            return RedirectToAction("AllStudents");
        }

        [HttpGet]
        public ActionResult ShowProfessors()
        {
            return View(_applicationContext.Users.ToList());
        }

        [HttpGet]
        public ActionResult AddSubject()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddSubject(Subject subject)
        {
            if (subject == null)
            {
                return Content("Предмет не создан.");
            }

            subject.ApplicationUserId = _applicationContext.Users
                .FirstOrDefault(user => user.UserName == subject.ApplicationUserId)?.Id;

            if (string.IsNullOrEmpty(subject.ApplicationUserId))
            {
                ModelState.AddModelError("", "Преподаватель не найден!");
                return RedirectToAction("AddSubject", subject);
            }

            _applicationContext.Subjects.Add(subject);

            _applicationContext.SaveChanges();

            return RedirectToAction("ShowSubjects");
        }

        [HttpGet]
        public ActionResult ShowSubjects()
        {
            return View(_applicationContext.Subjects.ToList());
        }

        [HttpGet]
        public ActionResult DeleteSubject(int id)
        {
            Subject subject = _applicationContext.Subjects.Find(id);
            if (subject == null)
            {
                return Content("Предмет не найден.");
            }

            _applicationContext.Entry(subject).State =
                EntityState.Deleted;

            _applicationContext.SaveChanges();
            return RedirectToAction("ShowSubjects");
        }

        #endregion
    }
}

Pagen/Views/Decanat/AddSubject.cshtml
@model Pagen.Models.Identity.Subject

@{
    ViewBag.Title = "AddSubject";
    Layout = "~/Views/Decanat/Decanat_Layout.cshtml";
}

<h2>Добавить предмет</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.NameSubject, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NameSubject, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NameSubject, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label>Логин преподавателя</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.ApplicationUserId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ApplicationUserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Pagen/Views/Decanat/AllStudents.cshtml
@using Pagen.Models.Identity
@model IEnumerable<Pagen.Models.Identity.Student>

@{
    ViewBag.Title = "AllStudents";
    Layout = "~/Views/Decanat/Decanat_Layout.cshtml";
}

<h2>Студенты</h2>

<p>
    @Html.ActionLink("Зачислить студента", "CreateStudent")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Group)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Surname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Patronymic)
        </th>
        <th></th>
    </tr>

    @foreach (Student item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Group)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Surname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Patronymic)
            </td>
            <td>
                @Html.ActionLink("Изменить", "EditStudent", new { id = item.Id }) |
                @Html.ActionLink("Удалить", "DeleteStudent", new { id = item.Id })
            </td>
        </tr>
    }

</table>

Pagen/Views/Decanat/CreateStudent.cshtml
@model Pagen.Models.Identity.Student

@{
    Layout = "~/Views/Decanat/Decanat_Layout.cshtml";
}

<h2>Зачислить студента</h2>


@using (Html.BeginForm("CreateStudent", "Decanat", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Group, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Group, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Group, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Surname, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Patronymic, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Patronymic, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Patronymic, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Pagen/Views/Decanat/Decanat_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/allcss")
    @if (IsSectionDefined("Css"))
    {
        @RenderSection("Css")
    }
    <link href="https://fonts.googleapis.com/css?family=Comfortaa" rel="stylesheet">
</head>
<body class="bg-light">

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/ajax")
    @Scripts.Render("~/bundles/bootstrap")
    @if (IsSectionDefined("Scripts"))
    {
        @RenderSection("Scripts")
    }
    <nav class="navbar navbar-expand-lg navbar-light bg-success">
        <a class="navbar-brand" href="#">Деканат менеджер</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "Home")">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("AllStudents", "Decanat")">Студенты</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("ShowProfessors", "Decanat")">Преподаватели</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("ShowSubjects", "Decanat")">Предметы</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Logout", "Account")">Выход</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container">
        @RenderBody()
    </div>
</body>
</html>

Pagen/Views/Decanat/EditStudent.cshtml
@model Pagen.Models.Identity.Student

@{
    Layout = "~/Views/Decanat/Decanat_Layout.cshtml";
}

<h2>EditStudents</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Student</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Group, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Group, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Group, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Surname, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Patronymic, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Patronymic, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Patronymic, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Pagen/Views/Decanat/ShowProfessors.cshtml
@using Pagen.Models
@model IEnumerable<Pagen.Models.ApplicationUser>

@{
    ViewBag.Title = "ShowProfessors";
    Layout = "~/Views/Decanat/Decanat_Layout.cshtml";
}

<h2>Преподаватели</h2>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Surname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Patronymic)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>

        <th></th>
    </tr>

    @foreach (ApplicationUser item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Surname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Patronymic)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
        </tr>
    }

</table>

Pagen/Views/Decanat/ShowSubjects.cshtml
@using Pagen.Models.Identity
@model IEnumerable<Pagen.Models.Identity.Subject>

@{
    ViewBag.Title = "ShowSubjects";
    Layout = "~/Views/Decanat/Decanat_Layout.cshtml";
}

<h2>Предметы</h2>

<p>
    @Html.ActionLink("Добавить новый", "AddSubject")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.NameSubject)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ApplicationUser.UserName)
        </th>
        <th></th>
    </tr>

    @foreach (Subject item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NameSubject)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ApplicationUser.UserName)
            </td>
            <td>
                @Html.ActionLink("Удалить", "DeleteSubject", new { id = item.Id })
            </td>
        </tr>
    }

</table>